name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 0.7.1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/logger_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: "0.7.0+2"
  sensors: ^0.4.0+1

  esys_flutter_share: #^1.0.2 #https://pub.dev/packages/esys_flutter_share/changelog
    #TODO: Change to release package when updated from 1.0.2
    git:
      url: git@github.com:FreeSK8/esys-flutter-share.git
      ref: nullsafety+embedding-2
